"""Fail-loud report body when structured fundamentals are missing."""

from __future__ import annotations

from typing import Any

from ..reporting import format_next_actions, format_rag_citation_section


def render_fatal_data_gap_sections(state: dict[str, Any], *, data_mode: str) -> tuple[list[str], str]:
    """Return (markdown lines, executive summary) for an incomplete-data run."""
    sections: list[str] = []

    def S(line: str = "") -> None:
        sections.append(line)

    companies = ", ".join(state.get("companies") or []) or "(none)"
    detail = state.get("data_gap_detail") or (
        "No computable structured fundamentals were available. "
        "Upload a filing PDF with extractable metrics or retry the configured live fundamentals provider."
    )
    S("# Incomplete Diligence Output (Fail-Loud Data Gap)")
    S("")
    S(f"**Companies:** {companies}")
    S("")
    S("## 1. Executive Summary")
    S("")
    S(detail)
    S("")
    S(
        "**Evidence Boundary:** This run produced no AST-verifiable revenue/EBITDA/R&D inputs. "
        "Market snapshots and LLM general knowledge alone are not treated as structured fundamentals. "
        "No ratios, SWOT, or investment positioning were invented."
    )
    S("")
    S("## 3. Financial Performance Analysis")
    S("")
    S(
        "Not available — fail-closed. Structured fundamentals were missing or non-computable "
        f"for: {companies}."
    )
    S("")
    S("## 4. Risk")
    S("")
    S(
        "**Data limitation risk (high):** Without extractable FY metrics, quantitative risk scoring "
        "and peer margin comparison are withheld rather than estimated."
    )
    S("")
    S("## 6. Compliance Review & Data Integrity")
    S("")
    S(
        "Fail-closed compliance path: the synthesizer refused to fabricate checkable metrics. "
        f"Gate expectation: `structured_source=none` for {companies}."
    )
    provider_summary = state.get("provider_error_summary") or {}
    if provider_summary.get("count"):
        S("")
        S(
            "**Provider error summary:** "
            f"transient={provider_summary.get('transient_count', 0)}, "
            f"truly_missing/unavailable={provider_summary.get('missing_count', 0)}, "
            f"other={provider_summary.get('other_count', 0)}, "
            f"by_class={provider_summary.get('by_class', {})}."
        )
    S("")
    S("## Appendix B. Methodology, Data Sources & Disclaimer")
    S("")
    if data_mode == "demo":
        S(
            "**Action Required:** Upload source filings (PDF) with extractable FY metrics, or query a "
            "company covered by the demo sample database."
        )
    else:
        S(
            "**Action Required:** Upload source filings (PDF) with extractable FY metrics, or retry the "
            "configured live fundamentals provider. To use local demo coverage, switch DATA_MODE=demo explicitly."
        )
    S("")
    for line in format_next_actions({**state, "workflow_status": "incomplete_data", "fatal_data_gap": True}):
        S(line)
    for line in format_rag_citation_section(state.get("rag_evidence")):
        S(line)
    if data_mode == "demo":
        S(
            "**Disclaimer:** DEMO MODE — incomplete output. This is research/demo only and does not "
            "constitute investment advice."
        )
    else:
        S(
            "**Disclaimer:** This incomplete report is generated by an AI-powered multi-agent system for "
            "research purposes only. It does not constitute investment advice, a solicitation, or a "
            "recommendation to buy or sell any security."
        )
    return sections, str(detail)
